import type { Metadata } from 'next'
import '../globals.css'
import localFont from 'next/font/local'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import LayoutContent from '@/components/common/LayoutContent'
import Script from 'next/script'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.korfit.co.kr'

const inter = localFont({
  src: '../../../public/fonts/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter',
  display: 'swap',
})

const pretendard = localFont({
  src: '../../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Cache-Control" content="public, max-age=3600" />
        <link
          rel="preload"
          href="/fonts/PretendardVariable.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />

        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://www.googletagmanager.com" crossOrigin="anonymous" />

        <style>{`
          html, body {
            margin: 0;
            padding: 0;
            background: white;
            font-family: var(--font-pretendard), system-ui, sans-serif;
          }
          main {
            width: 375px;
            margin: 0 auto;
            background: white;
          }
        `}</style>

        {/* Schema.org 구조화된 데이터 */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'Organization',
              name: 'Korfit',
              url: `${SITE_URL}`,
              logo: `${SITE_URL}/logo.svg`,
              description: 'Kickstart your job in Korea with a hiring roadmap for foreigners.',
              sameAs: ['https://www.instagram.com/korfit_official'],
            }),
          }}
        />
      </head>

      <body className={`${inter.variable} ${pretendard.variable} font-sans antialiased`}>
        <ReactQueryProvider>
          <LayoutContent>{children}</LayoutContent>
        </ReactQueryProvider>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_KEY}&libraries=services&autoload=false`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  )
}
